apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grid-station-project
  namespace: argocd
spec:
  description: Project for grid station applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: grid-station
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
