apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-exporter
  namespace: grid-station
data:
  exporter.py: |    
    from prometheus_client import start_http_server, Gauge
    import time
    import csv
    import os
    import sys

    # Set up logging to stdout
    def log(message):
        print(message, flush=True)
        sys.stdout.flush()

    log("Starting Prometheus exporter...")

    # Create Prometheus metrics
    TOTAL_POWER = Gauge("grid_station_total_power", "Total power in kW")
    REACTIVE_POWER = Gauge("grid_station_reactive_power", "Reactive power in kVAr")
    FREQUENCY = Gauge("grid_station_frequency", "Grid frequency in Hz")
    VOLTAGE = Gauge("grid_station_voltage", "Voltage in V")
    CURRENT = Gauge("grid_station_current", "Current in A")
    POWER_FACTOR = Gauge("grid_station_power_factor", "Power factor")
    BREAKER_STATUS = Gauge("grid_station_breaker_status", "Breaker status (1=closed, 0=open)")
    TRANSFORMER_TEMP = Gauge("grid_station_transformer_temp", "Transformer temperature in C")
    LINE_IMPEDANCE = Gauge("grid_station_line_impedance", "Line impedance in ohms")
    HARMONIC_DISTORTION = Gauge("grid_station_harmonic_distortion", "Harmonic distortion in %")

    def read_latest_data():
        datafile = "/data/measurements.csv"
    
        if not os.path.exists(datafile):
            log(f"Data file not found: {datafile}")
            return
    
        try:
            with open(datafile, "r") as f:
                log(f"Reading data file: {datafile}")
                csv_reader = csv.DictReader(f)  # Use DictReader for more reliable column access
            
                # Get all rows
                rows = list(csv_reader)
                if not rows:
                    log("CSV file has no data rows")
                    return
            
                # Get last line
                last_row = rows[-1]
                log(f"Processing last row: {dict(last_row)}")
            
                # Parse values with explicit column names and error handling
                try:
                    if 'TotW' in last_row:
                        TOTAL_POWER.set(float(last_row['TotW']))
                    if 'TotVAr' in last_row:
                        REACTIVE_POWER.set(float(last_row['TotVAr']))
                    if 'Hz' in last_row:
                        FREQUENCY.set(float(last_row['Hz']))
                    if 'Voltage' in last_row:
                        VOLTAGE.set(float(last_row['Voltage']))
                    if 'Current' in last_row:
                        CURRENT.set(float(last_row['Current']))
                    if 'PowerFactor' in last_row:
                        POWER_FACTOR.set(float(last_row['PowerFactor']))
                    if 'BreakerStatus' in last_row:
                        BREAKER_STATUS.set(int(last_row['BreakerStatus']))
                    if 'TransformerTemp' in last_row:
                        TRANSFORMER_TEMP.set(float(last_row['TransformerTemp']))
                    if 'LineImpedance' in last_row:
                        LINE_IMPEDANCE.set(float(last_row['LineImpedance']))
                    if 'HarmonicDistortion' in last_row:
                        HARMONIC_DISTORTION.set(float(last_row['HarmonicDistortion']))
                
                    log("Successfully updated metrics with latest values")
                except (ValueError, KeyError) as e:
                    log(f"Error parsing row values: {e}")
        except Exception as e:
            log(f"Error reading data file: {e}")

    if __name__ == "__main__":
        try:
            # Start up the server to expose the metrics
            start_http_server(9100)
            log("Prometheus exporter started on port 9100")
    
            # Update metrics every 5 seconds
            while True:
                read_latest_data()
                time.sleep(5)
        except Exception as e:
            log(f"Fatal error in main loop: {e}")
