apiVersion: v1
kind: ConfigMap
metadata:
  name: iec61850-config
  namespace: grid-station
data:
  iec61850-server.conf: |
    # IEC61850 Server Configuration
    server_name=IEC61850_SIMULATOR
    model_file=/config/model.icd
    report_interval=5000
    log_level=INFO
  model.icd: |
    <?xml version="1.0" encoding="UTF-8"?>
    <SCL xmlns="http://www.iec.ch/61850/2003/SCL">
      <Header id="Simple IED Model" version="1.0"/>
      <IED name="SIMULATOR">
        <AccessPoint name="AP1">
          <Server>
            <LDevice inst="Simulated_Device">
              <LN0 lnClass="LLN0" inst="">
                <DataObject name="Mod" type="INC_1_Mod"/>
                <DataObject name="Health" type="INS_1_Health"/>
              </LN0>
              <LN prefix="" lnClass="MMXU" inst="1">
                <DataObject name="TotW" type="MV_1_TotW"/>
                <DataObject name="TotVAr" type="MV_1_TotVAr"/>
                <DataObject name="Hz" type="MV_1_Hz"/>
              </LN>
            </LDevice>
          </Server>
        </AccessPoint>
      </IED>
    </SCL>
