apiVersion: apps/v1
kind: Deployment
metadata:
  name: scada-interface
  namespace: grid-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scada-interface
  template:
    metadata:
      labels:
        app: scada-interface
    spec:
      containers:
      - name: opcua-server
        image: python:3.9-slim
        ports:
        - containerPort: 4840
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install opcua requests &&
            mkdir -p /app &&
            cp /scripts/server.py /app/ &&
            cd /app && 
            python server.py
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: server-script
          mountPath: /scripts
        env:
        - name: SERVER_CONFIG
          value: "/config/opcua-server.conf"
        - name: DATA_SOURCE_URL
          value: "http://ml-processing:8001/api/data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: opcua-config
      - name: server-script
        configMap:
          name: scada-interface-handler
