apiVersion: v1
kind: Service
metadata:
  name: scada-interface
  namespace: grid-station
spec:
  selector:
    app: scada-interface
  ports:
  - port: 4840
    targetPort: 4840
  clusterIP: 10.240.0.12
