apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-processing
  namespace: grid-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-processing
  template:
    metadata:
      labels:
        app: ml-processing
    spec:
      containers:
      - name: ml-processor
        image: pytorch/pytorch:latest
        ports:
        - containerPort: 8001
        workingDir: /app
        command: ["python"]
        args: ["/app/app.py"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: model-storage
          mountPath: /models
        - name: demo-files
          mountPath: /app
        env:
        - name: CONFIG_PATH
          value: "/config/config.yaml"
        - name: MODEL_DIR
          value: "/models"
        - name: DATA_SOURCE_URL
          value: "http://ec61850-simulator:102/data"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: config-volume
        configMap:
          name: ml-processing-config
      - name: model-storage
        persistentVolumeClaim:
          claimName: ml-model-storage
      - name: demo-files
        configMap:
          name: ml-demo-files
