apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grid-station-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ec61850-simulator
  endpoints:
  - port: metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - grid-station
