apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grid-station-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ec61850-simulator
      k8s-app: grid-station-metrics
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - grid-station
