apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter
  namespace: grid-station
  labels:
    app: ec61850-simulator
spec:
  selector:
    app: ec61850-simulator
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
  type: ClusterIP
