apiVersion: v1
kind: Service
metadata:
  name: ec61850-simulator
  namespace: grid-station
spec:
  selector:
    app: ec61850-simulator
  ports:
  - port: 102
    targetPort: 102
  clusterIP: 10.240.0.10
