apiVersion: v1
kind: Service
metadata:
  name: ec61850-simulator
  namespace: grid-station
  labels:
    app: ec61850-simulator
    k8s-app: grid-station-metrics
spec:
  selector:
    app: ec61850-simulator
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
  type: ClusterIP
